title: Pratik Jain
logo: /assets/img/new_pic.jpg
description: <p> AI Solutions Engineer </p>
             <p> Contact - official.jain.pratik@gmail.com </p>
             <p> Education - B.Tech. (IIT Indore 2017-2021) </p>       
show_downloads: true
theme: jekyll-theme-minimal
