title: Pratik Jain
logo: /assets/img/new_pic.jpg
description: 
AI Solutions Engineer
Contact - official.jain.pratik@gmail.com 
Education - B.Tech. (IIT Indore - 2021)           
show_downloads: true
theme: jekyll-theme-minimal
