title: Pratik Jain
logo: /assets/img/profilepic.jpg
description: 
    <p> I am Pratik, an AI Software Engineer with half a decade of experience specializing in building and managing AI projects in the financial domain. My expertise encompasses product management, data science, programming, data analytics, and database management. I excel in delivering impactful projects that align with business objectives. </p>
    <p> Contact - official.jain.pratik@gmail.com </p>
show_downloads: true
theme: jekyll-theme-minimal
