title: Pratik Jain
logo: /assets/img/profilepic.jpg
description: 
    <p> I am Pratik, an AI Software Engineer with half a decade of experience specializing in building and managing AI projects in the financial domain. My expertise encompasses product management, data science, programming, data analytics, and database management. I am proficient in utilizing a robust technical stack, including Python, PySpark, SQL, NoSQL, C++, and Pandas, to design and deploy scalable AI solutions. Dedicated to optimizing processes and driving innovation, I excel in delivering impactful projects that align with business objectives. </p>
    <p> Contact - official.jain.pratik@gmail.com </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
